Support minimal, remove sngl, various updates.

diff --git a/install-base b/install-base
--- a/install-base
+++ b/install-base
@@ -6,7 +6,7 @@
 
 usage()
 {
-	echo "usage: install-base [-hv] -c <config> [-n <name>] -r <release> -z <zone>" >&2
+	echo "usage: install-base [-hv] -c <config> -n <name> -r <release> -z <zone>" >&2
 	exit 1
 }
 
@@ -24,13 +24,13 @@ done
 #
 # Sanity checks.
 #
-for var in config release zone; do
+for var in config name release zone; do
 	if [ -z "${!var}" ]; then
 		echo "ERROR: ${var} not set" >&2
 		usage
 	fi
 done
-if [[ ! "${config}" =~ ^([0-9]{4}Q[0-9]|trunk)-(i386|x86_64|sngl|multiarch) ]]; then
+if [[ ! "${config}" =~ ^([0-9]{4}Q[0-9]|trunk)-(i386|x86_64|multiarch) ]]; then
 	echo "ERROR: Unsupported configuration: ${config}" >&2
 	exit 1
 fi
@@ -45,91 +45,95 @@ if [ "$(dirname $0)" != "." ]; then
 fi
 
 #
-# Set up configuration variables for the specified target.
+# The basic set of packages from the minimal bootstrap.
 #
-IMAGE_PACKAGES="
-bmake
-bootstrap-mk-files
-bsdinstall
-bzip2
-changepass
-coreutils
-curl
-diffutils
-findutils
-gawk
-gcc47-libs
-gettext-lib
-grep
-gsed
-gtar-base
-less
-libarchive
-libiconv
-mozilla-rootcerts
-nawk
-nbsed
-ncurses
-nodejs
-openssl
-patch
-pkg_alternatives
-pkg_install
-pkg_install-info
-pkgin
-postfix
-readline
-smtools
-sqlite3
-sudo
-wget
-xz
-zlib
-"
-if [[ "${config}" =~ sngl ]]; then
-	CRLE_DPATH_32="/system/lib:/system/usr/lib"
-	CRLE_DPATH_64="/system/lib/64:/system/usr/lib/64"
-	CRLE_TPATH_32="/system/lib/secure:/system/usr/lib/secure"
-	CRLE_TPATH_64="/system/lib/secure/64:/system/usr/lib/secure/64"
-	IMAGE_MANDIRS="/usr/share/man:/system/usr/share/man"
-	# Base vim doesn't work due to missing terminfo.
-	IMAGE_PACKAGES="${IMAGE_PACKAGES} vim"
-	IMAGE_PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin"
-	IMAGE_PREFIX="/usr"
-	IMAGE_SYSCONFDIR="/etc"
-	IMAGE_DOC="http://wiki.joyent.com/jpc2/SNGL+Instance"
-else
-	CRLE_DPATH_32="/lib:/usr/lib"
-	CRLE_DPATH_64="/lib/64:/usr/lib/64"
-	CRLE_TPATH_32="/lib/secure:/usr/lib/secure"
-	CRLE_TPATH_64="/lib/secure/64:/usr/lib/secure/64"
-	IMAGE_MANDIRS="/opt/local/man:/usr/share/man"
-	IMAGE_PATH="/usr/local/sbin:/usr/local/bin:/opt/local/sbin:/opt/local/bin:/usr/sbin:/usr/bin:/sbin"
-	IMAGE_PREFIX="/opt/local"
-	IMAGE_SYSCONFDIR="/opt/local/etc"
-	IMAGE_DOC="http://wiki.joyent.com/jpc2/SmartMachine+Base"
-fi
-# Older images require groff.
-if [[ "${config}" =~ ^(201[012]|2013Q[12]) ]]; then
-	IMAGE_PACKAGES="${IMAGE_PACKAGES} groff"
-fi
-if [[ "${config}" =~ ^(2013Q[34]|201[4-9]) ]]; then
-	IMAGE_PACKAGES="${IMAGE_PACKAGES} rsyslog zoneinit"
-fi
+bootstrap_packages=(
+	bmake
+	bootstrap-mk-files
+	bsdinstall
+	bzip2
+	gcc47-libs
+	gettext-lib
+	libarchive
+	libiconv
+	mozilla-rootcerts
+	nawk
+	nbsed
+	ncurses
+	openssl
+	pkg_alternatives
+	pkg_install
+	pkg_install-info
+	pkgin
+	pkgsrc-gnupg-keys
+	readline
+	sqlite3
+	xz
+	zlib
+)
+#
+# Minimal images only add that which is required to get a zone to boot.
+#
+minimal_packages=(
+	${bootstrap_packages[@]}
+	changepass
+	smtools
+	zoneinit
+)
+#
+# Base adds a set of common packages on top of minimal.
+#
+base_packages=(
+	${minimal_packages[@]}
+	coreutils
+	curl
+	diffutils
+	findutils
+	gawk
+	grep
+	gsed
+	gtar-base
+	less
+	nodejs
+	patch
+	postfix
+	rsyslog
+	sudo
+	wget
+)
+
+#
+# Common settings.
+#
+CRLE_DPATH_32="/lib:/usr/lib"
+CRLE_DPATH_64="/lib/64:/usr/lib/64"
+CRLE_TPATH_32="/lib/secure:/usr/lib/secure"
+CRLE_TPATH_64="/lib/secure/64:/usr/lib/secure/64"
+IMAGE_MANDIRS="/opt/local/man:/usr/share/man"
+IMAGE_PATH="/usr/local/sbin:/usr/local/bin:/opt/local/sbin:/opt/local/bin:/usr/sbin:/usr/bin:/sbin"
+IMAGE_PREFIX="/opt/local"
+IMAGE_SYSCONFDIR="/opt/local/etc"
 IMAGE_PRODUCT="Joyent Instance"
 IMAGE_SHORTPRODUCT="Instance"
 IMAGE_BRANCH="${config%-*}"
 IMAGE_ARCH="${config##*-}"
+IMAGE_NAME="${name}"
 IMAGE_VERSION="${release}"
-
-if [ -n "${name}" ]; then
-	IMAGE_NAME="${name}"
-else
-	IMAGE_NAME="${IMAGE_ARCH}"
-fi
-
 IMAGE_CSHPATH=$(echo ${IMAGE_PATH} | sed -e 's,:, ,g')
-IMAGE_PACKAGES=$(echo ${IMAGE_PACKAGES} | tr '\n' ' ')
+
+#
+# Per-image settings.
+#
+if [[ "${name}" =~ ^base ]]; then
+	IMAGE_DOC="https://docs.joyent.com/images/smartos/base"
+	IMAGE_PACKAGES="${base_packages[@]}"
+elif [[ "${name}" =~ ^minimal ]]; then
+	IMAGE_DOC="https://docs.joyent.com/images/smartos/minimal"
+	IMAGE_PACKAGES="${minimal_packages[@]}"
+else
+	echo "ERROR: Unsupported image name '${name}'" >&2
+	exit 1
+fi
 
 #
 # Ok, we should have all the configuration setup we need, now we start
@@ -167,15 +171,17 @@ do
 	done
 done
 #
-# Install IMAGE_SYSCONFDIR files into the correct location
+# Install IMAGE_SYSCONFDIR files into the correct location for base images.
 #
-for f in $(find overlay/sysconfdir -type f)
-do
-	basef=${f##overlay/sysconfdir/}
-	echo "Installing ${IMAGE_SYSCONFDIR}/${basef}"
-	mkdir -p ${zoneroot}${IMAGE_SYSCONFDIR}/$(dirname ${basef})
-	sed -e "${sedsubst}" ${f} >${zoneroot}${IMAGE_SYSCONFDIR}/${basef}
-done
+if [[ "${name}" =~ ^base ]]; then
+	for f in $(find overlay/sysconfdir -type f)
+	do
+		basef=${f##overlay/sysconfdir/}
+		echo "Installing ${IMAGE_SYSCONFDIR}/${basef}"
+		mkdir -p ${zoneroot}${IMAGE_SYSCONFDIR}/$(dirname ${basef})
+		sed -e "${sedsubst}" ${f} >${zoneroot}${IMAGE_SYSCONFDIR}/${basef}
+	done
+fi
 
 echo "Logging into ${zone} to run /root/customize"
 zlogin ${zone} /root/customize
