Skip SSL verification downloading bootstrap.
The proto image does not have any root certificates to use, and we're
now redirecting all HTTP to HTTPS on pkgsrc.smartos.org.

diff --git a/overlay/root/customize b/overlay/root/customize
--- a/overlay/root/customize
+++ b/overlay/root/customize
@@ -46,7 +46,7 @@ export PATH
 
 if [ ! -f ${tempdir}/$(basename ${PKGSRC_BOOTSTRAP}) ]; then
 	echo -n "Downloading pkgsrc bootstrap..."
-	(cd ${tempdir} && curl -O ${PKGSRC_BOOTSTRAP}) >&5 2>&5 || fail "ERROR!"
+	(cd ${tempdir} && curl -kOL ${PKGSRC_BOOTSTRAP}) >&5 2>&5 || fail "ERROR!"
 	echo "done."
 
 	echo -n "Extracting pkgsrc bootstrap..."
